// Generates SHOT_LIST.md (minute-by-minute) from src/scenes.ts + src/shots.ts + src/timings.json.
import {buildSync} from 'esbuild';
import fs from 'node:fs';
const out = new URL('./.shotlist-bundle.mjs', import.meta.url).pathname;
buildSync({stdin: {contents: "export {SCENES, CHAPTER_TITLES} from './scenes'; export {SHOTS, searchLinks} from './shots';", resolveDir: new URL('../src', import.meta.url).pathname, loader: 'ts'}, bundle: true, format: 'esm', platform: 'node', outfile: out});
const {SCENES, CHAPTER_TITLES, SHOTS, searchLinks} = await import(out);
fs.unlinkSync(out);
const T = JSON.parse(fs.readFileSync(new URL('../src/timings.json', import.meta.url)));
const avail = JSON.parse(fs.readFileSync(new URL('../src/available.json', import.meta.url)));

const mmss = (s) => `${Math.floor(s / 60)}:${String(Math.floor(s % 60)).padStart(2, '0')}`;
const short = (t, n = 14) => { const w = t.split(/\s+/); return w.length > n ? w.slice(0, n).join(' ') + '…' : t; };
const ov = (o) => {
  if (!o) return '';
  switch (o.type) {
    case 'stat': return `Stat: **${o.value}** ${o.label}`;
    case 'bars': return `Bar chart: ${o.title} (${o.items.map((i) => `${i.label} ${i.display}`).join(' vs ')})`;
    case 'quote': return `Quote card: "${o.text}"`;
    case 'callout': return `Text: **${o.text}**`;
    case 'flow': return `Supply map: ${o.active.length ? o.active.join(' + ') : 'China only'} → China`;
    case 'route': return `Route: ${o.steps.map((s) => s.big).join(' · ')}`;
    case 'timeline': return `Timeline: ${o.points.map((p) => p.year).join(' → ')}`;
    case 'price': return `Price drop: ${o.to}`;
    case 'stamp': return `Stamp: ${o.text}`;
    case 'location': return `Location tag: ${o.text}`;
    case 'note': return `Research note: "${o.text}"`;
    case 'map': return `Animated map: ${o.map}`;
    case 'scribbles': return `Marker notes: ${o.items.map((i) => i.text.replace(/\n/g, ' ')).join(', ')}`;
  }
};
const kindLabel = {stock: 'Stock (Pexels/Pixabay)', commons: 'Wikimedia Commons (credit author)', ai: 'AI-generated'};

let md = `# Shot list: China Buys 90% of the World's Durian Exports\n\n`;
md += `Auto-generated by \`npm run shotlist\`. Times are from the real voiceover, so they match the rendered video.\n\n`;
md += `- **Visual** = the B-roll file to drop in \`public/broll/<id>.mp4\` (or .jpg/.png).\n- **Graphic** = drawn automatically by Remotion; you don't need to source it.\n- ✅ = file already in \`public/broll/\`.\n\n`;
let t = 0;
const FPS = 30, f = (s) => Math.round(s * FPS) / FPS;
const total = T.reduce((a, c, i) => a + f(c.duration + 0.6) + (CHAPTER_TITLES[c.id] ? 2.5 : 0) + (i === 0 ? 4.5 : 0), 0) + 12;
md += `**Runtime:** ${mmss(total)} (voiceover ${mmss(T.reduce((a, c) => a + c.duration, 0))} + cards)\n\n`;
T.forEach((ch, i) => {
  const title = CHAPTER_TITLES[ch.id];
  if (title) { md += `\n## ${mmss(t)} · ${i === 7 ? 'Close' : `Chapter ${i}`}: ${title}\n\n_Chapter card, 2.5 s_\n\n`; t += 2.5; }
  else md += `\n## ${mmss(t)} · Cold open\n\n`;
  md += `| Time | Narration | Visual (B-roll) | Graphic | Citation |\n|---|---|---|---|---|\n`;
  ch.paras.forEach((p, j) => {
    const b = SCENES[ch.id][j];
    const id = (b.broll || []).find((x) => !x.startsWith('ai-')) || (b.broll || [])[0];
    const s = id ? SHOTS[id] : null;
    const vis = id ? `${avail[id] ? '✅ ' : ''}\`${id}\`: ${s ? s.what : ''}` : '(graphic only)';
    md += `| ${mmss(t + p.start)} | ${short(p.text).replace(/\|/g, '/')} | ${vis} | ${ov(b.overlay) || ''} | ${b.source || ''} |\n`;
  });
  t += f(ch.duration + 0.6);
  if (i === 0) { md += `\n**${mmss(t)} · Title card** (4.5 s): CHINA BUYS 90% OF THE WORLD'S DURIAN EXPORTS\n`; t += 4.5; }
});
md += `\n## ${mmss(t)} · End card (12 s)\n\nAdd YouTube end-screen elements over the two dashed boxes.\n`;

md += `\n---\n\n# Download checklist (${Object.keys(SHOTS).length} clips)\n\nSave each file as \`public/broll/<id>.mp4\` (or .jpg/.png), then run \`npm run render\`.\n\n`;
for (const kind of ['stock', 'commons', 'ai']) {
  md += `\n## ${kindLabel[kind]}\n\n`;
  for (const [id, s] of Object.entries(SHOTS)) {
    if (s.kind !== kind) continue;
    md += `- [${avail[id] ? 'x' : ' '}] **\`${id}\`**: ${s.what}\n`;
    for (const p of s.picks || []) md += `  - Pick: [${p.label}](${p.url})\n`;
    if (kind !== 'ai') md += `  - Search: ${searchLinks(s.query).map((l) => `[${l.label}: "${s.query}"](${l.url})`).join(' · ')}\n`;
  }
}
fs.writeFileSync(new URL('../SHOT_LIST.md', import.meta.url), md);
console.log('SHOT_LIST.md written');
